const countries = {
  supported: [
    { value: "AL", label: "Albania" },
    { value: "AU", label: "Australia" },
    { value: "AT", label: "Austria" },
    { value: "BE", label: "Belgium" },
    { value: "BR", label: "Brazil" },
    { value: "CA", label: "Canada" },
    { value: "DK", label: "Denmark" },
    { value: "FI", label: "Finland" },
    { value: "FR", label: "France" },
    { value: "DE", label: "Germany" },
    { value: "HK", label: "Hong Kong [China]" },
    { value: "IE", label: "Ireland" },
    { value: "IT", label: "Italy" },
    { value: "JP", label: "Japan" },
    { value: "XK", label: "Kosovo" },
    { value: "LU", label: "Luxembourg" },
    { value: "MX", label: "Mexico" },
    { value: "NL", label: "Netherlands" },
    { value: "NZ", label: "New Zealand" },
    { value: "NO", label: "Norway" },
    { value: "PT", label: "Portugal" },
    { value: "SG", label: "Singapore" },
    { value: "ES", label: "Spain" },
    { value: "SE", label: "Sweden" },
    { value: "CH", label: "Switzerland" },
    { value: "GB", label: "United Kingdom" },
    { value: "US", label: "United States" }
  ],

  states: {
    US: [
      { value: "AL", label: "Alabama" },
      { value: "AK", label: "Alaska" },
      { value: "AZ", label: "Arizona" },
      { value: "AR", label: "Arkansas" },
      { value: "CA", label: "California" },
      { value: "CO", label: "Colorado" },
      { value: "CT", label: "Connecticut" },
      { value: "DE", label: "Delaware" },
      { value: "DC", label: "District Of Columbia" },
      { value: "FL", label: "Florida" },
      { value: "GA", label: "Georgia" },
      { value: "HI", label: "Hawaii" },
      { value: "ID", label: "Idaho" },
      { value: "IL", label: "Illinois" },
      { value: "IN", label: "Indiana" },
      { value: "IA", label: "Iowa" },
      { value: "KS", label: "Kansas" },
      { value: "KY", label: "Kentucky" },
      { value: "LA", label: "Louisiana" },
      { value: "ME", label: "Maine" },
      { value: "MD", label: "Maryland" },
      { value: "MA", label: "Massachusetts" },
      { value: "MI", label: "Michigan" },
      { value: "MN", label: "Minnesota" },
      { value: "MS", label: "Mississippi" },
      { value: "MO", label: "Missouri" },
      { value: "MT", label: "Montana" },
      { value: "NE", label: "Nebraska" },
      { value: "NV", label: "Nevada" },
      { value: "NH", label: "New Hampshire" },
      { value: "NJ", label: "New Jersey" },
      { value: "NM", label: "New Mexico" },
      { value: "NY", label: "New York" },
      { value: "NC", label: "North Carolina" },
      { value: "ND", label: "North Dakota" },
      { value: "OH", label: "Ohio" },
      { value: "OK", label: "Oklahoma" },
      { value: "OR", label: "Oregon" },
      { value: "PA", label: "Pennsylvania" },
      { value: "RI", label: "Rhode Island" },
      { value: "SC", label: "South Carolina" },
      { value: "SD", label: "South Dakota" },
      { value: "TN", label: "Tennessee" },
      { value: "TX", label: "Texas" },
      { value: "UT", label: "Utah" },
      { value: "VT", label: "Vermont" },
      { value: "VA", label: "Virginia" },
      { value: "WA", label: "Washington" },
      { value: "WV", label: "West Virginia" },
      { value: "WI", label: "Wisconsin" },
      { value: "WY", label: "Wyoming" }
    ],

    CA: [
      { value: "AB", label: "Alberta" },
      { value: "BC", label: "British Columbia" },
      { value: "MB", label: "Manitoba" },
      { value: "NB", label: "New Brunswick" },
      { value: "NL", label: "Newfoundland and Labrador" },
      { value: "NS", label: "Nova Scotia" },
      { value: "ON", label: "Ontario" },
      { value: "PE", label: "Prince Edward Island" },
      { value: "QC", label: "Quebec" },
      { value: "SK", label: "Saskatchewan" },
      { value: "NT", label: "Northwest Territories" },
      { value: "NU", label: "Nunavut" },
      { value: "YT", label: "Yukon" }
    ]
  },

  countries: [
    { value: "AF", label: "Afghanistan" },
    { value: "AL", label: "Albania" },
    { value: "DZ", label: "Algeria" },
    { value: "AS", label: "American Samoa" },
    { value: "AD", label: "Andorra" },
    { value: "AO", label: "Angola" },
    { value: "AI", label: "Anguilla" },
    { value: "AQ", label: "Antarctica" },
    { value: "AG", label: "Antigua & Barbuda" },
    { value: "AR", label: "Argentina" },
    { value: "AM", label: "Armenia" },
    { value: "AW", label: "Aruba" },
    { value: "AC", label: "Ascension Island" },
    { value: "AU", label: "Australia" },
    { value: "AT", label: "Austria" },
    { value: "AZ", label: "Azerbaijan" },
    { value: "BS", label: "Bahamas" },
    { value: "BH", label: "Bahrain" },
    { value: "BD", label: "Bangladesh" },
    { value: "BB", label: "Barbados" },
    { value: "BY", label: "Belarus" },
    { value: "BE", label: "Belgium" },
    { value: "BZ", label: "Belize" },
    { value: "BJ", label: "Benin" },
    { value: "BM", label: "Bermuda" },
    { value: "BT", label: "Bhutan" },
    { value: "BO", label: "Bolivia" },
    { value: "BA", label: "Bosnia & Herzegovina" },
    { value: "BW", label: "Botswana" },
    { value: "BV", label: "Bouvet Island" },
    { value: "BR", label: "Brazil" },
    { value: "IO", label: "British Indian Ocean Territory" },
    { value: "VG", label: "British Virgin Islands" },
    { value: "BN", label: "Brunei" },
    { value: "BG", label: "Bulgaria" },
    { value: "BF", label: "Burkina Faso" },
    { value: "BI", label: "Burundi" },
    { value: "KH", label: "Cambodia" },
    { value: "CM", label: "Cameroon" },
    { value: "CA", label: "Canada" },
    { value: "IC", label: "Canary Islands" },
    { value: "CV", label: "Cape Verde" },
    { value: "BQ", label: "Caribbean Netherlands" },
    { value: "KY", label: "Cayman Islands" },
    { value: "CF", label: "Central African Republic" },
    { value: "EA", label: "Ceuta & Melilla" },
    { value: "TD", label: "Chad" },
    { value: "CL", label: "Chile" },
    { value: "CN", label: "China" },
    { value: "CX", label: "Christmas Island" },
    { value: "CP", label: "Clipperton Island" },
    { value: "CC", label: "Cocos [Keeling] Islands" },
    { value: "CO", label: "Colombia" },
    { value: "KM", label: "Comoros" },
    { value: "CG", label: "Congo - Brazzaville" },
    { value: "CD", label: "Congo - Kinshasa" },
    { value: "CK", label: "Cook Islands" },
    { value: "CR", label: "Costa Rica" },
    { value: "HR", label: "Croatia" },
    { value: "CU", label: "Cuba" },
    { value: "CW", label: "Curaçao" },
    { value: "CY", label: "Cyprus" },
    { value: "CZ", label: "Czech Republic" },
    { value: "CI", label: "Côte d'Ivoire" },
    { value: "DK", label: "Denmark" },
    { value: "DG", label: "Diego Garcia" },
    { value: "DJ", label: "Djibouti" },
    { value: "DM", label: "Dominica" },
    { value: "DO", label: "Dominican Republic" },
    { value: "EC", label: "Ecuador" },
    { value: "EG", label: "Egypt" },
    { value: "SV", label: "El Salvador" },
    { value: "GQ", label: "Equatorial Guinea" },
    { value: "ER", label: "Eritrea" },
    { value: "EE", label: "Estonia" },
    { value: "ET", label: "Ethiopia" },
    { value: "FK", label: "Falkland Islands" },
    { value: "FO", label: "Faroe Islands" },
    { value: "FJ", label: "Fiji" },
    { value: "FI", label: "Finland" },
    { value: "FR", label: "France" },
    { value: "GF", label: "French Guiana" },
    { value: "PF", label: "French Polynesia" },
    { value: "TF", label: "French Southern Territories" },
    { value: "GA", label: "Gabon" },
    { value: "GM", label: "Gambia" },
    { value: "GE", label: "Georgia" },
    { value: "DE", label: "Germany" },
    { value: "GH", label: "Ghana" },
    { value: "GI", label: "Gibraltar" },
    { value: "GR", label: "Greece" },
    { value: "GL", label: "Greenland" },
    { value: "GD", label: "Grenada" },
    { value: "GP", label: "Guadeloupe" },
    { value: "GU", label: "Guam" },
    { value: "GT", label: "Guatemala" },
    { value: "GG", label: "Guernsey" },
    { value: "GN", label: "Guinea" },
    { value: "GW", label: "Guinea-Bissau" },
    { value: "GY", label: "Guyana" },
    { value: "HT", label: "Haiti" },
    { value: "HM", label: "Heard & McDonald Islands" },
    { value: "HN", label: "Honduras" },
    { value: "HK", label: "Hong Kong [China]" },
    { value: "HU", label: "Hungary" },
    { value: "IS", label: "Iceland" },
    { value: "IN", label: "India" },
    { value: "ID", label: "Indonesia" },
    { value: "IR", label: "Iran" },
    { value: "IQ", label: "Iraq" },
    { value: "IE", label: "Ireland" },
    { value: "IM", label: "Isle of Man" },
    { value: "IL", label: "Israel" },
    { value: "IT", label: "Italy" },
    { value: "JM", label: "Jamaica" },
    { value: "JP", label: "Japan" },
    { value: "JE", label: "Jersey" },
    { value: "JO", label: "Jordan" },
    { value: "KZ", label: "Kazakhstan" },
    { value: "KE", label: "Kenya" },
    { value: "KI", label: "Kiribati" },
    { value: "XK", label: "Kosovo" },
    { value: "KW", label: "Kuwait" },
    { value: "KG", label: "Kyrgyzstan" },
    { value: "LA", label: "Laos" },
    { value: "LV", label: "Latvia" },
    { value: "LB", label: "Lebanon" },
    { value: "LS", label: "Lesotho" },
    { value: "LR", label: "Liberia" },
    { value: "LY", label: "Libya" },
    { value: "LI", label: "Liechtenstein" },
    { value: "LT", label: "Lithuania" },
    { value: "LU", label: "Luxembourg" },
    { value: "MO", label: "Macau [China]" },
    { value: "MK", label: "Macedonia" },
    { value: "MG", label: "Madagascar" },
    { value: "MW", label: "Malawi" },
    { value: "MY", label: "Malaysia" },
    { value: "MV", label: "Maldives" },
    { value: "ML", label: "Mali" },
    { value: "MT", label: "Malta" },
    { value: "MH", label: "Marshall Islands" },
    { value: "MQ", label: "Martinique" },
    { value: "MR", label: "Mauritania" },
    { value: "MU", label: "Mauritius" },
    { value: "YT", label: "Mayotte" },
    { value: "MX", label: "Mexico" },
    { value: "FM", label: "Micronesia" },
    { value: "MD", label: "Moldova" },
    { value: "MC", label: "Monaco" },
    { value: "MN", label: "Mongolia" },
    { value: "ME", label: "Montenegro" },
    { value: "MS", label: "Montserrat" },
    { value: "MA", label: "Morocco" },
    { value: "MZ", label: "Mozambique" },
    { value: "MM", label: "Myanmar [Burma]" },
    { value: "NA", label: "Namibia" },
    { value: "NR", label: "Nauru" },
    { value: "NP", label: "Nepal" },
    { value: "NL", label: "Netherlands" },
    { value: "NC", label: "New Caledonia" },
    { value: "NZ", label: "New Zealand" },
    { value: "NI", label: "Nicaragua" },
    { value: "NE", label: "Niger" },
    { value: "NG", label: "Nigeria" },
    { value: "NU", label: "Niue" },
    { value: "NF", label: "Norfolk Island" },
    { value: "KP", label: "North Korea" },
    { value: "MP", label: "Northern Mariana Islands" },
    { value: "NO", label: "Norway" },
    { value: "OM", label: "Oman" },
    { value: "PK", label: "Pakistan" },
    { value: "PW", label: "Palau" },
    { value: "PS", label: "Palestinian Territories" },
    { value: "PA", label: "Panama" },
    { value: "PG", label: "Papua New Guinea" },
    { value: "PY", label: "Paraguay" },
    { value: "PE", label: "Peru" },
    { value: "PH", label: "Philippines" },
    { value: "PN", label: "Pitcairn Islands" },
    { value: "PL", label: "Poland" },
    { value: "PT", label: "Portugal" },
    { value: "PR", label: "Puerto Rico" },
    { value: "QA", label: "Qatar" },
    { value: "RO", label: "Romania" },
    { value: "RU", label: "Russia" },
    { value: "RW", label: "Rwanda" },
    { value: "RE", label: "Réunion" },
    { value: "WS", label: "Samoa" },
    { value: "SM", label: "San Marino" },
    { value: "SA", label: "Saudi Arabia" },
    { value: "SN", label: "Senegal" },
    { value: "RS", label: "Serbia" },
    { value: "SC", label: "Seychelles" },
    { value: "SL", label: "Sierra Leone" },
    { value: "SG", label: "Singapore" },
    { value: "SX", label: "Sint Maarten" },
    { value: "SK", label: "Slovakia" },
    { value: "SI", label: "Slovenia" },
    { value: "GS", label: "So. Georgia & So. Sandwich Isl." },
    { value: "SB", label: "Solomon Islands" },
    { value: "SO", label: "Somalia" },
    { value: "ZA", label: "South Africa" },
    { value: "KR", label: "South Korea" },
    { value: "SS", label: "South Sudan" },
    { value: "ES", label: "Spain" },
    { value: "LK", label: "Sri Lanka" },
    { value: "BL", label: "St. Barthélemy" },
    { value: "SH", label: "St. Helena" },
    { value: "KN", label: "St. Kitts & Nevis" },
    { value: "LC", label: "St. Lucia" },
    { value: "MF", label: "St. Martin" },
    { value: "PM", label: "St. Pierre & Miquelon" },
    { value: "VC", label: "St. Vincent & Grenadines" },
    { value: "SD", label: "Sudan" },
    { value: "SR", label: "Suriname" },
    { value: "SJ", label: "Svalbard & Jan Mayen" },
    { value: "SZ", label: "Swaziland" },
    { value: "SE", label: "Sweden" },
    { value: "CH", label: "Switzerland" },
    { value: "SY", label: "Syria" },
    { value: "ST", label: "São Tomé & Príncipe" },
    { value: "TW", label: "Taiwan" },
    { value: "TJ", label: "Tajikistan" },
    { value: "TZ", label: "Tanzania" },
    { value: "TH", label: "Thailand" },
    { value: "TL", label: "Timor-Leste" },
    { value: "TG", label: "Togo" },
    { value: "TK", label: "Tokelau" },
    { value: "TO", label: "Tonga" },
    { value: "TT", label: "Trinidad & Tobago" },
    { value: "TA", label: "Tristan da Cunha" },
    { value: "TN", label: "Tunisia" },
    { value: "TR", label: "Turkey" },
    { value: "TM", label: "Turkmenistan" },
    { value: "TC", label: "Turks & Caicos Islands" },
    { value: "TV", label: "Tuvalu" },
    { value: "UM", label: "U.S. Outlying Islands" },
    { value: "VI", label: "U.S. Virgin Islands" },
    { value: "UG", label: "Uganda" },
    { value: "UA", label: "Ukraine" },
    { value: "AE", label: "United Arab Emirates" },
    { value: "GB", label: "United Kingdom" },
    { value: "US", label: "United States" },
    { value: "UY", label: "Uruguay" },
    { value: "UZ", label: "Uzbekistan" },
    { value: "VU", label: "Vanuatu" },
    { value: "VA", label: "Vatican City" },
    { value: "VE", label: "Venezuela" },
    { value: "VN", label: "Vietnam" },
    { value: "WF", label: "Wallis & Futuna" },
    { value: "EH", label: "Western Sahara" },
    { value: "YE", label: "Yemen" },
    { value: "ZM", label: "Zambia" },
    { value: "ZW", label: "Zimbabwe" },
    { value: "AX", label: "Åland Islands" }
  ],

  phoneCodes: [
    { value: "AL", label: "355" },
    { value: "DZ", label: "213" },
    { value: "AD", label: "376" },
    { value: "AO", label: "244" },
    { value: "AI", label: "1264" },
    { value: "AG", label: "1268" },
    { value: "AR", label: "54" },
    { value: "AM", label: "374" },
    { value: "AW", label: "297" },
    { value: "AU", label: "61" },
    { value: "AT", label: "43" },
    { value: "AZ", label: "994" },
    { value: "BS", label: "1242" },
    { value: "BH", label: "973" },
    { value: "BD", label: "880" },
    { value: "BB", label: "1246" },
    { value: "BY", label: "375" },
    { value: "BE", label: "32" },
    { value: "BZ", label: "501" },
    { value: "BJ", label: "229" },
    { value: "BM", label: "1441" },
    { value: "BT", label: "975" },
    { value: "BO", label: "591" },
    { value: "BA", label: "387" },
    { value: "BW", label: "267" },
    { value: "BR", label: "55" },
    { value: "BN", label: "673" },
    { value: "BG", label: "359" },
    { value: "BF", label: "226" },
    { value: "BI", label: "257" },
    { value: "KH", label: "855" },
    { value: "CM", label: "237" },
    { value: "CA", label: "1" },
    { value: "CV", label: "238" },
    { value: "KY", label: "1345" },
    { value: "CF", label: "236" },
    { value: "CL", label: "56" },
    { value: "CN", label: "86" },
    { value: "CO", label: "57" },
    { value: "KM", label: "269" },
    { value: "CG", label: "242" },
    { value: "CK", label: "682" },
    { value: "CR", label: "506" },
    { value: "HR", label: "385" },
    { value: "CU", label: "53" },
    { value: "CY", label: "357" },
    { value: "CZ", label: "42" },
    { value: "DK", label: "45" },
    { value: "DJ", label: "253" },
    { value: "DM", label: "1809" },
    { value: "DO", label: "1809" },
    { value: "EC", label: "593" },
    { value: "EG", label: "20" },
    { value: "SV", label: "503" },
    { value: "GQ", label: "240" },
    { value: "ER", label: "291" },
    { value: "EE", label: "372" },
    { value: "ET", label: "251" },
    { value: "FK", label: "500" },
    { value: "FO", label: "298" },
    { value: "FJ", label: "679" },
    { value: "FI", label: "358" },
    { value: "FR", label: "33" },
    { value: "GF", label: "594" },
    { value: "PF", label: "689" },
    { value: "GA", label: "241" },
    { value: "GM", label: "220" },
    { value: "GE", label: "7880" },
    { value: "DE", label: "49" },
    { value: "GH", label: "233" },
    { value: "GI", label: "350" },
    { value: "GR", label: "30" },
    { value: "GL", label: "299" },
    { value: "GD", label: "1473" },
    { value: "GP", label: "590" },
    { value: "GU", label: "671" },
    { value: "GT", label: "502" },
    { value: "GN", label: "224" },
    { value: "GW", label: "245" },
    { value: "GY", label: "592" },
    { value: "HT", label: "509" },
    { value: "HN", label: "504" },
    { value: "HK", label: "852" },
    { value: "HU", label: "36" },
    { value: "IS", label: "354" },
    { value: "IN", label: "91" },
    { value: "ID", label: "62" },
    { value: "IR", label: "98" },
    { value: "IQ", label: "964" },
    { value: "IE", label: "353" },
    { value: "IL", label: "972" },
    { value: "IT", label: "39" },
    { value: "JM", label: "1876" },
    { value: "JP", label: "81" },
    { value: "JO", label: "962" },
    { value: "KZ", label: "7" },
    { value: "KE", label: "254" },
    { value: "KI", label: "686" },
    { value: "KP", label: "850" },
    { value: "KR", label: "82" },
    { value: "KW", label: "965" },
    { value: "KG", label: "996" },
    { value: "LA", label: "856" },
    { value: "LV", label: "371" },
    { value: "LB", label: "961" },
    { value: "LS", label: "266" },
    { value: "LR", label: "231" },
    { value: "LY", label: "218" },
    { value: "LI", label: "417" },
    { value: "LT", label: "370" },
    { value: "LU", label: "352" },
    { value: "MO", label: "853" },
    { value: "MK", label: "389" },
    { value: "MG", label: "261" },
    { value: "MW", label: "265" },
    { value: "MY", label: "60" },
    { value: "MV", label: "960" },
    { value: "ML", label: "223" },
    { value: "MT", label: "356" },
    { value: "MH", label: "692" },
    { value: "MQ", label: "596" },
    { value: "MR", label: "222" },
    { value: "YT", label: "269" },
    { value: "MX", label: "52" },
    { value: "FM", label: "691" },
    { value: "MD", label: "373" },
    { value: "MC", label: "377" },
    { value: "MN", label: "976" },
    { value: "MS", label: "1664" },
    { value: "MA", label: "212" },
    { value: "MZ", label: "258" },
    { value: "MM", label: "95" },
    { value: "NA", label: "264" },
    { value: "NR", label: "674" },
    { value: "NP", label: "977" },
    { value: "NL", label: "31" },
    { value: "NC", label: "687" },
    { value: "NZ", label: "64" },
    { value: "NI", label: "505" },
    { value: "NE", label: "227" },
    { value: "NG", label: "234" },
    { value: "NU", label: "683" },
    { value: "NF", label: "672" },
    { value: "MP", label: "670" },
    { value: "NO", label: "47" },
    { value: "OM", label: "968" },
    { value: "PW", label: "680" },
    { value: "PA", label: "507" },
    { value: "PG", label: "675" },
    { value: "PY", label: "595" },
    { value: "PE", label: "51" },
    { value: "PH", label: "63" },
    { value: "PL", label: "48" },
    { value: "PT", label: "351" },
    { value: "PR", label: "1787" },
    { value: "QA", label: "974" },
    { value: "RE", label: "262" },
    { value: "RO", label: "40" },
    { value: "RU", label: "7" },
    { value: "RW", label: "250" },
    { value: "SM", label: "378" },
    { value: "ST", label: "239" },
    { value: "SA", label: "966" },
    { value: "SN", label: "221" },
    { value: "SC", label: "248" },
    { value: "SL", label: "232" },
    { value: "SG", label: "65" },
    { value: "SK", label: "421" },
    { value: "SI", label: "386" },
    { value: "SB", label: "677" },
    { value: "SO", label: "252" },
    { value: "ZA", label: "27" },
    { value: "ES", label: "34" },
    { value: "LK", label: "94" },
    { value: "SH", label: "290" },
    { value: "KN", label: "1869" },
    { value: "LC", label: "1758" },
    { value: "SD", label: "249" },
    { value: "SR", label: "597" },
    { value: "SZ", label: "268" },
    { value: "SE", label: "46" },
    { value: "CH", label: "41" },
    { value: "SY", label: "963" },
    { value: "TW", label: "886" },
    { value: "TJ", label: "7" },
    { value: "TH", label: "66" },
    { value: "TG", label: "228" },
    { value: "TO", label: "676" },
    { value: "TT", label: "1868" },
    { value: "TN", label: "216" },
    { value: "TR", label: "90" },
    { value: "TM", label: "993" },
    { value: "TC", label: "1649" },
    { value: "TV", label: "688" },
    { value: "UG", label: "256" },
    { value: "GB", label: "44" },
    { value: "UA", label: "380" },
    { value: "AE", label: "971" },
    { value: "UY", label: "598" },
    { value: "US", label: "1" },
    { value: "UZ", label: "7" },
    { value: "VU", label: "678" },
    { value: "VA", label: "379" },
    { value: "VE", label: "58" },
    { value: "VN", label: "84" },
    { value: "VG", label: "84" },
    { value: "VI", label: "84" },
    { value: "WF", label: "681" },
    { value: "YE", label: "967" },
    { value: "ZM", label: "260" },
    { value: "ZW", label: "263" },
    { value: "AF", label: "93" },
    { value: "AS", label: "1" },
    { value: "AQ", label: "672" },
    { value: "AC", label: "290" },
    { value: "BV", label: "47" },
    { value: "IO", label: "246" },
    { value: "TD", label: "235" },
    { value: "CX", label: "672" },
    { value: "CI", label: "225" },
    { value: "GG", label: "44" },
    { value: "XK", label: "383" },
    { value: "ME", label: "382" },
    { value: "PK", label: "92" },
    { value: "PS", label: "970" },
    { value: "PN", label: "672" },
    { value: "WS", label: "685" },
    { value: "RS", label: "381" },
    { value: "EH", label: "212" },
    { value: "TZ", label: "255" },
    { value: "MU", label: "230" },
    { value: "JE", label: "44" }
  ]
};

module.exports = countries;
